swagger: "2.0"
info:
  description: The Adara Traveler Intelligence API allows realtime intelligence on a traveler's lifetime value.
  version: "1.0.0"
  title: Traveler Intelligence API
consumes:
  - application/json
produces:
  - application/json

basePath: /api/v1.0/

# Paths supported by the server application
paths:
  /score/{cookie_id}:
    get:
      operationId: api.score.get.get_score_by_cookie_id
      tags:
        - Intelligence
      summary: Get a cookie's TVS score
      description: Get a tvs score for a particular cookie_id
      parameters:
        - name: cookie_id
          in: path
          type: integer
          description: the cookie ID
          required: True
      responses:
        200:
          description: Successfully returned list of intel scores
          schema:
            type: object
            properties:
              cookie_id:
                type: integer
              score:
                type: number  
  /scoreEmail/{dp_id}:
    get:
      operationId: api.scoreEmail.get.get_Score_Email_by_dp_id
      tags:
        - Email,score,Intelligence
      summary: Get a score,email by dp_id
      description: Get a score,email for a cookie by dp_id, return empty list if there is no 
      parameters:
        - name: dp_id
          in: path
          type: integer
          description: the dataprovider_id
          required: True
      responses:
        200:
          description: Successfully returned list of intel scores
          schema:
            type: object
            properties:
              cookie_id:
                type: integer
              score:
                type: number
              email:
                type: string  
  

          