swagger: "2.0"
info:
  description: The Adara Traveler Intelligence API allows realtime intelligence on a traveler's lifetime value.
  version: "1.0.0"
  title: Traveler Intelligence API
consumes:
  - application/json
produces:
  - application/json

basePath: /api/v1.0/

# Paths supported by the server application
paths:
  /{dpid}:
    get:
      operationId: api.get.get_by_dpid
      tags:
        - TVS
      summary: Get a list of the cookies and TVS scores
      description: Get a list of the TVS scores tied to cookies for a particular DPID
      parameters:
        - name: dpid
          in: path
          type: integer
          description: Data provider ID to filter the TVS scores
          required: True
        - name: length
          in: query
          type: integer
          description: Number of scores to return
          required: false
        - name: offset
          in: query
          type: integer
          description: Offset from beginning of list where to start in the scores
          required: false
      responses:
        200:
          description: Successfully returned list of intel scores
          schema:
            type: array
            items:
              properties:
                cookie_id:
                  type: integer
                score:
                  type: number
                timestamp:
                  type: string
